INSERT INTO countries(id, code, name) VALUES ('AND', 'AD', 'Andorra');
INSERT INTO countries(id, code, name) VALUES ('ARE', 'AE', 'United Arab Emirates');
INSERT INTO countries(id, code, name) VALUES ('AFG', 'AF', 'Afghanistan');
INSERT INTO countries(id, code, name) VALUES ('ATG', 'AG', 'Antigua and Barbuda');
INSERT INTO countries(id, code, name) VALUES ('AIA', 'AI', 'Anguilla');
INSERT INTO countries(id, code, name) VALUES ('ALB', 'AL', 'Albania');
INSERT INTO countries(id, code, name) VALUES ('ARM', 'AM', 'Armenia');
INSERT INTO countries(id, code, name) VALUES ('AGO', 'AO', 'Angola');
INSERT INTO countries(id, code, name) VALUES ('ATA', 'AQ', 'Antarctica');
INSERT INTO countries(id, code, name) VALUES ('ARG', 'AR', 'Argentina');
INSERT INTO countries(id, code, name) VALUES ('ASM', 'AS', 'American Samoa');
INSERT INTO countries(id, code, name) VALUES ('AUT', 'AT', 'Austria');
INSERT INTO countries(id, code, name) VALUES ('AUS', 'AU', 'Australia');
INSERT INTO countries(id, code, name) VALUES ('ABW', 'AW', 'Aruba');
INSERT INTO countries(id, code, name) VALUES ('ALA', 'AX', 'Åland');
INSERT INTO countries(id, code, name) VALUES ('AZE', 'AZ', 'Azerbaijan');
INSERT INTO countries(id, code, name) VALUES ('BIH', 'BA', 'Bosnia and Herzegovina');
INSERT INTO countries(id, code, name) VALUES ('BRB', 'BB', 'Barbados');
INSERT INTO countries(id, code, name) VALUES ('BGD', 'BD', 'Bangladesh');
INSERT INTO countries(id, code, name) VALUES ('BEL', 'BE', 'Belgium');
INSERT INTO countries(id, code, name) VALUES ('BFA', 'BF', 'Burkina Faso');
INSERT INTO countries(id, code, name) VALUES ('BGR', 'BG', 'Bulgaria');
INSERT INTO countries(id, code, name) VALUES ('BHR', 'BH', 'Bahrain');
INSERT INTO countries(id, code, name) VALUES ('BDI', 'BI', 'Burundi');
INSERT INTO countries(id, code, name) VALUES ('BEN', 'BJ', 'Benin');
INSERT INTO countries(id, code, name) VALUES ('BLM', 'BL', 'Saint Barthélemy');
INSERT INTO countries(id, code, name) VALUES ('BMU', 'BM', 'Bermuda');
INSERT INTO countries(id, code, name) VALUES ('BRN', 'BN', 'Brunei');
INSERT INTO countries(id, code, name) VALUES ('BOL', 'BO', 'Bolivia');
INSERT INTO countries(id, code, name) VALUES ('BES', 'BQ', 'Bonaire, Sint Eustatius, and Saba');
INSERT INTO countries(id, code, name) VALUES ('BRA', 'BR', 'Brazil');
INSERT INTO countries(id, code, name) VALUES ('BHS', 'BS', 'Bahamas');
INSERT INTO countries(id, code, name) VALUES ('BTN', 'BT', 'Bhutan');
INSERT INTO countries(id, code, name) VALUES ('BVT', 'BV', 'Bouvet Island');
INSERT INTO countries(id, code, name) VALUES ('BWA', 'BW', 'Botswana');
INSERT INTO countries(id, code, name) VALUES ('BLR', 'BY', 'Belarus');
INSERT INTO countries(id, code, name) VALUES ('BLZ', 'BZ', 'Belize');
INSERT INTO countries(id, code, name) VALUES ('CAN', 'CA', 'Canada');
INSERT INTO countries(id, code, name) VALUES ('CCK', 'CC', 'Cocos [Keeling] Islands');
INSERT INTO countries(id, code, name) VALUES ('COD', 'CD', 'DR Congo');
INSERT INTO countries(id, code, name) VALUES ('CAF', 'CF', 'Central African Republic');
INSERT INTO countries(id, code, name) VALUES ('COG', 'CG', 'Congo Republic');
INSERT INTO countries(id, code, name) VALUES ('CHE', 'CH', 'Switzerland');
INSERT INTO countries(id, code, name) VALUES ('CIV', 'CI', 'Ivory Coast');
INSERT INTO countries(id, code, name) VALUES ('COK', 'CK', 'Cook Islands');
INSERT INTO countries(id, code, name) VALUES ('CHL', 'CL', 'Chile');
INSERT INTO countries(id, code, name) VALUES ('CMR', 'CM', 'Cameroon');
INSERT INTO countries(id, code, name) VALUES ('CHN', 'CN', 'China');
INSERT INTO countries(id, code, name) VALUES ('COL', 'CO', 'Colombia');
INSERT INTO countries(id, code, name) VALUES ('CRI', 'CR', 'Costa Rica');
INSERT INTO countries(id, code, name) VALUES ('CUB', 'CU', 'Cuba');
INSERT INTO countries(id, code, name) VALUES ('CPV', 'CV', 'Cabo Verde');
INSERT INTO countries(id, code, name) VALUES ('CUW', 'CW', 'Curaçao');
INSERT INTO countries(id, code, name) VALUES ('CXR', 'CX', 'Christmas Island');
INSERT INTO countries(id, code, name) VALUES ('CYP', 'CY', 'Cyprus');
INSERT INTO countries(id, code, name) VALUES ('CZE', 'CZ', 'Czechia');
INSERT INTO countries(id, code, name) VALUES ('DEU', 'DE', 'Germany');
INSERT INTO countries(id, code, name) VALUES ('DJI', 'DJ', 'Djibouti');
INSERT INTO countries(id, code, name) VALUES ('DNK', 'DK', 'Denmark');
INSERT INTO countries(id, code, name) VALUES ('DMA', 'DM', 'Dominica');
INSERT INTO countries(id, code, name) VALUES ('DOM', 'DO', 'Dominican Republic');
INSERT INTO countries(id, code, name) VALUES ('DZA', 'DZ', 'Algeria');
INSERT INTO countries(id, code, name) VALUES ('ECU', 'EC', 'Ecuador');
INSERT INTO countries(id, code, name) VALUES ('EST', 'EE', 'Estonia');
INSERT INTO countries(id, code, name) VALUES ('EGY', 'EG', 'Egypt');
INSERT INTO countries(id, code, name) VALUES ('ESH', 'EH', 'Western Sahara');
INSERT INTO countries(id, code, name) VALUES ('ERI', 'ER', 'Eritrea');
INSERT INTO countries(id, code, name) VALUES ('ESP', 'ES', 'Spain');
INSERT INTO countries(id, code, name) VALUES ('ETH', 'ET', 'Ethiopia');
INSERT INTO countries(id, code, name) VALUES ('FIN', 'FI', 'Finland');
INSERT INTO countries(id, code, name) VALUES ('FJI', 'FJ', 'Fiji');
INSERT INTO countries(id, code, name) VALUES ('FLK', 'FK', 'Falkland Islands');
INSERT INTO countries(id, code, name) VALUES ('FSM', 'FM', 'Micronesia');
INSERT INTO countries(id, code, name) VALUES ('FRO', 'FO', 'Faroe Islands');
INSERT INTO countries(id, code, name) VALUES ('FRA', 'FR', 'France');
INSERT INTO countries(id, code, name) VALUES ('GAB', 'GA', 'Gabon');
INSERT INTO countries(id, code, name) VALUES ('GBR', 'GB', 'United Kingdom');
INSERT INTO countries(id, code, name) VALUES ('GRD', 'GD', 'Grenada');
INSERT INTO countries(id, code, name) VALUES ('GEO', 'GE', 'Georgia');
INSERT INTO countries(id, code, name) VALUES ('GUF', 'GF', 'French Guiana');
INSERT INTO countries(id, code, name) VALUES ('GGY', 'GG', 'Guernsey');
INSERT INTO countries(id, code, name) VALUES ('GHA', 'GH', 'Ghana');
INSERT INTO countries(id, code, name) VALUES ('GIB', 'GI', 'Gibraltar');
INSERT INTO countries(id, code, name) VALUES ('GRL', 'GL', 'Greenland');
INSERT INTO countries(id, code, name) VALUES ('GMB', 'GM', 'Gambia');
INSERT INTO countries(id, code, name) VALUES ('GIN', 'GN', 'Guinea');
INSERT INTO countries(id, code, name) VALUES ('GLP', 'GP', 'Guadeloupe');
INSERT INTO countries(id, code, name) VALUES ('GNQ', 'GQ', 'Equatorial Guinea');
INSERT INTO countries(id, code, name) VALUES ('GRC', 'GR', 'Greece');
INSERT INTO countries(id, code, name) VALUES ('SGS', 'GS', 'South Georgia and South Sandwich Islands');
INSERT INTO countries(id, code, name) VALUES ('GTM', 'GT', 'Guatemala');
INSERT INTO countries(id, code, name) VALUES ('GUM', 'GU', 'Guam');
INSERT INTO countries(id, code, name) VALUES ('GNB', 'GW', 'Guinea-Bissau');
INSERT INTO countries(id, code, name) VALUES ('GUY', 'GY', 'Guyana');
INSERT INTO countries(id, code, name) VALUES ('HKG', 'HK', 'Hong Kong');
INSERT INTO countries(id, code, name) VALUES ('HMD', 'HM', 'Heard Island and McDonald Islands');
INSERT INTO countries(id, code, name) VALUES ('HND', 'HN', 'Honduras');
INSERT INTO countries(id, code, name) VALUES ('HRV', 'HR', 'Croatia');
INSERT INTO countries(id, code, name) VALUES ('HTI', 'HT', 'Haiti');
INSERT INTO countries(id, code, name) VALUES ('HUN', 'HU', 'Hungary');
INSERT INTO countries(id, code, name) VALUES ('IDN', 'ID', 'Indonesia');
INSERT INTO countries(id, code, name) VALUES ('IRL', 'IE', 'Ireland');
INSERT INTO countries(id, code, name) VALUES ('ISR', 'IL', 'Israel');
INSERT INTO countries(id, code, name) VALUES ('IMN', 'IM', 'Isle of Man');
INSERT INTO countries(id, code, name) VALUES ('IND', 'IN', 'India');
INSERT INTO countries(id, code, name) VALUES ('IOT', 'IO', 'British Indian Ocean Territory');
INSERT INTO countries(id, code, name) VALUES ('IRQ', 'IQ', 'Iraq');
INSERT INTO countries(id, code, name) VALUES ('IRN', 'IR', 'Iran');
INSERT INTO countries(id, code, name) VALUES ('ISL', 'IS', 'Iceland');
INSERT INTO countries(id, code, name) VALUES ('ITA', 'IT', 'Italy');
INSERT INTO countries(id, code, name) VALUES ('JEY', 'JE', 'Jersey');
INSERT INTO countries(id, code, name) VALUES ('JAM', 'JM', 'Jamaica');
INSERT INTO countries(id, code, name) VALUES ('JOR', 'JO', 'Jordan');
INSERT INTO countries(id, code, name) VALUES ('JPN', 'JP', 'Japan');
INSERT INTO countries(id, code, name) VALUES ('KEN', 'KE', 'Kenya');
INSERT INTO countries(id, code, name) VALUES ('KGZ', 'KG', 'Kyrgyzstan');
INSERT INTO countries(id, code, name) VALUES ('KHM', 'KH', 'Cambodia');
INSERT INTO countries(id, code, name) VALUES ('KIR', 'KI', 'Kiribati');
INSERT INTO countries(id, code, name) VALUES ('COM', 'KM', 'Comoros');
INSERT INTO countries(id, code, name) VALUES ('KNA', 'KN', 'St Kitts and Nevis');
INSERT INTO countries(id, code, name) VALUES ('PRK', 'KP', 'North Korea');
INSERT INTO countries(id, code, name) VALUES ('KOR', 'KR', 'South Korea');
INSERT INTO countries(id, code, name) VALUES ('KWT', 'KW', 'Kuwait');
INSERT INTO countries(id, code, name) VALUES ('CYM', 'KY', 'Cayman Islands');
INSERT INTO countries(id, code, name) VALUES ('KAZ', 'KZ', 'Kazakhstan');
INSERT INTO countries(id, code, name) VALUES ('LAO', 'LA', 'Laos');
INSERT INTO countries(id, code, name) VALUES ('LBN', 'LB', 'Lebanon');
INSERT INTO countries(id, code, name) VALUES ('LCA', 'LC', 'Saint Lucia');
INSERT INTO countries(id, code, name) VALUES ('LIE', 'LI', 'Liechtenstein');
INSERT INTO countries(id, code, name) VALUES ('LKA', 'LK', 'Sri Lanka');
INSERT INTO countries(id, code, name) VALUES ('LBR', 'LR', 'Liberia');
INSERT INTO countries(id, code, name) VALUES ('LSO', 'LS', 'Lesotho');
INSERT INTO countries(id, code, name) VALUES ('LTU', 'LT', 'Lithuania');
INSERT INTO countries(id, code, name) VALUES ('LUX', 'LU', 'Luxembourg');
INSERT INTO countries(id, code, name) VALUES ('LVA', 'LV', 'Latvia');
INSERT INTO countries(id, code, name) VALUES ('LBY', 'LY', 'Libya');
INSERT INTO countries(id, code, name) VALUES ('MAR', 'MA', 'Morocco');
INSERT INTO countries(id, code, name) VALUES ('MCO', 'MC', 'Monaco');
INSERT INTO countries(id, code, name) VALUES ('MDA', 'MD', 'Moldova');
INSERT INTO countries(id, code, name) VALUES ('MNE', 'ME', 'Montenegro');
INSERT INTO countries(id, code, name) VALUES ('MAF', 'MF', 'Saint Martin');
INSERT INTO countries(id, code, name) VALUES ('MDG', 'MG', 'Madagascar');
INSERT INTO countries(id, code, name) VALUES ('MHL', 'MH', 'Marshall Islands');
INSERT INTO countries(id, code, name) VALUES ('MKD', 'MK', 'North Macedonia');
INSERT INTO countries(id, code, name) VALUES ('MLI', 'ML', 'Mali');
INSERT INTO countries(id, code, name) VALUES ('MMR', 'MM', 'Myanmar');
INSERT INTO countries(id, code, name) VALUES ('MNG', 'MN', 'Mongolia');
INSERT INTO countries(id, code, name) VALUES ('MAC', 'MO', 'Macao');
INSERT INTO countries(id, code, name) VALUES ('MNP', 'MP', 'Northern Mariana Islands');
INSERT INTO countries(id, code, name) VALUES ('MTQ', 'MQ', 'Martinique');
INSERT INTO countries(id, code, name) VALUES ('MRT', 'MR', 'Mauritania');
INSERT INTO countries(id, code, name) VALUES ('MSR', 'MS', 'Montserrat');
INSERT INTO countries(id, code, name) VALUES ('MLT', 'MT', 'Malta');
INSERT INTO countries(id, code, name) VALUES ('MUS', 'MU', 'Mauritius');
INSERT INTO countries(id, code, name) VALUES ('MDV', 'MV', 'Maldives');
INSERT INTO countries(id, code, name) VALUES ('MWI', 'MW', 'Malawi');
INSERT INTO countries(id, code, name) VALUES ('MEX', 'MX', 'Mexico');
INSERT INTO countries(id, code, name) VALUES ('MYS', 'MY', 'Malaysia');
INSERT INTO countries(id, code, name) VALUES ('MOZ', 'MZ', 'Mozambique');
INSERT INTO countries(id, code, name) VALUES ('NAM', 'NA', 'Namibia');
INSERT INTO countries(id, code, name) VALUES ('NCL', 'NC', 'New Caledonia');
INSERT INTO countries(id, code, name) VALUES ('NER', 'NE', 'Niger');
INSERT INTO countries(id, code, name) VALUES ('NFK', 'NF', 'Norfolk Island');
INSERT INTO countries(id, code, name) VALUES ('NGA', 'NG', 'Nigeria');
INSERT INTO countries(id, code, name) VALUES ('NIC', 'NI', 'Nicaragua');
INSERT INTO countries(id, code, name) VALUES ('NLD', 'NL', 'Netherlands');
INSERT INTO countries(id, code, name) VALUES ('NOR', 'NO', 'Norway');
INSERT INTO countries(id, code, name) VALUES ('NPL', 'NP', 'Nepal');
INSERT INTO countries(id, code, name) VALUES ('NRU', 'NR', 'Nauru');
INSERT INTO countries(id, code, name) VALUES ('NIU', 'NU', 'Niue');
INSERT INTO countries(id, code, name) VALUES ('NZL', 'NZ', 'New Zealand');
INSERT INTO countries(id, code, name) VALUES ('OMN', 'OM', 'Oman');
INSERT INTO countries(id, code, name) VALUES ('PAN', 'PA', 'Panama');
INSERT INTO countries(id, code, name) VALUES ('PER', 'PE', 'Peru');
INSERT INTO countries(id, code, name) VALUES ('PYF', 'PF', 'French Polynesia');
INSERT INTO countries(id, code, name) VALUES ('PNG', 'PG', 'Papua New Guinea');
INSERT INTO countries(id, code, name) VALUES ('PHL', 'PH', 'Philippines');
INSERT INTO countries(id, code, name) VALUES ('PAK', 'PK', 'Pakistan');
INSERT INTO countries(id, code, name) VALUES ('POL', 'PL', 'Poland');
INSERT INTO countries(id, code, name) VALUES ('SPM', 'PM', 'Saint Pierre and Miquelon');
INSERT INTO countries(id, code, name) VALUES ('PCN', 'PN', 'Pitcairn Islands');
INSERT INTO countries(id, code, name) VALUES ('PRI', 'PR', 'Puerto Rico');
INSERT INTO countries(id, code, name) VALUES ('PSE', 'PS', 'Palestine');
INSERT INTO countries(id, code, name) VALUES ('PRT', 'PT', 'Portugal');
INSERT INTO countries(id, code, name) VALUES ('PLW', 'PW', 'Palau');
INSERT INTO countries(id, code, name) VALUES ('PRY', 'PY', 'Paraguay');
INSERT INTO countries(id, code, name) VALUES ('QAT', 'QA', 'Qatar');
INSERT INTO countries(id, code, name) VALUES ('REU', 'RE', 'Réunion');
INSERT INTO countries(id, code, name) VALUES ('ROU', 'RO', 'Romania');
INSERT INTO countries(id, code, name) VALUES ('SRB', 'RS', 'Serbia');
INSERT INTO countries(id, code, name) VALUES ('RUS', 'RU', 'Russia');
INSERT INTO countries(id, code, name) VALUES ('RWA', 'RW', 'Rwanda');
INSERT INTO countries(id, code, name) VALUES ('SAU', 'SA', 'Saudi Arabia');
INSERT INTO countries(id, code, name) VALUES ('SLB', 'SB', 'Solomon Islands');
INSERT INTO countries(id, code, name) VALUES ('SYC', 'SC', 'Seychelles');
INSERT INTO countries(id, code, name) VALUES ('SDN', 'SD', 'Sudan');
INSERT INTO countries(id, code, name) VALUES ('SWE', 'SE', 'Sweden');
INSERT INTO countries(id, code, name) VALUES ('SGP', 'SG', 'Singapore');
INSERT INTO countries(id, code, name) VALUES ('SHN', 'SH', 'Saint Helena');
INSERT INTO countries(id, code, name) VALUES ('SVN', 'SI', 'Slovenia');
INSERT INTO countries(id, code, name) VALUES ('SJM', 'SJ', 'Svalbard and Jan Mayen');
INSERT INTO countries(id, code, name) VALUES ('SVK', 'SK', 'Slovakia');
INSERT INTO countries(id, code, name) VALUES ('SLE', 'SL', 'Sierra Leone');
INSERT INTO countries(id, code, name) VALUES ('SMR', 'SM', 'San Marino');
INSERT INTO countries(id, code, name) VALUES ('SEN', 'SN', 'Senegal');
INSERT INTO countries(id, code, name) VALUES ('SOM', 'SO', 'Somalia');
INSERT INTO countries(id, code, name) VALUES ('SUR', 'SR', 'Suriname');
INSERT INTO countries(id, code, name) VALUES ('SSD', 'SS', 'South Sudan');
INSERT INTO countries(id, code, name) VALUES ('STP', 'ST', 'São Tomé and Príncipe');
INSERT INTO countries(id, code, name) VALUES ('SLV', 'SV', 'El Salvador');
INSERT INTO countries(id, code, name) VALUES ('SXM', 'SX', 'Sint Maarten');
INSERT INTO countries(id, code, name) VALUES ('SYR', 'SY', 'Syria');
INSERT INTO countries(id, code, name) VALUES ('SWZ', 'SZ', 'Eswatini');
INSERT INTO countries(id, code, name) VALUES ('TCA', 'TC', 'Turks and Caicos Islands');
INSERT INTO countries(id, code, name) VALUES ('TCD', 'TD', 'Chad');
INSERT INTO countries(id, code, name) VALUES ('ATF', 'TF', 'French Southern Territories');
INSERT INTO countries(id, code, name) VALUES ('TGO', 'TG', 'Togo');
INSERT INTO countries(id, code, name) VALUES ('THA', 'TH', 'Thailand');
INSERT INTO countries(id, code, name) VALUES ('TJK', 'TJ', 'Tajikistan');
INSERT INTO countries(id, code, name) VALUES ('TKL', 'TK', 'Tokelau');
INSERT INTO countries(id, code, name) VALUES ('TLS', 'TL', 'Timor-Leste');
INSERT INTO countries(id, code, name) VALUES ('TKM', 'TM', 'Turkmenistan');
INSERT INTO countries(id, code, name) VALUES ('TUN', 'TN', 'Tunisia');
INSERT INTO countries(id, code, name) VALUES ('TON', 'TO', 'Tonga');
INSERT INTO countries(id, code, name) VALUES ('TUR', 'TR', 'Turkey');
INSERT INTO countries(id, code, name) VALUES ('TTO', 'TT', 'Trinidad and Tobago');
INSERT INTO countries(id, code, name) VALUES ('TUV', 'TV', 'Tuvalu');
INSERT INTO countries(id, code, name) VALUES ('TWN', 'TW', 'Taiwan');
INSERT INTO countries(id, code, name) VALUES ('TZA', 'TZ', 'Tanzania');
INSERT INTO countries(id, code, name) VALUES ('UKR', 'UA', 'Ukraine');
INSERT INTO countries(id, code, name) VALUES ('UGA', 'UG', 'Uganda');
INSERT INTO countries(id, code, name) VALUES ('UMI', 'UM', 'U.S. Minor Outlying Islands');
INSERT INTO countries(id, code, name) VALUES ('USA', 'US', 'United States');
INSERT INTO countries(id, code, name) VALUES ('URY', 'UY', 'Uruguay');
INSERT INTO countries(id, code, name) VALUES ('UZB', 'UZ', 'Uzbekistan');
INSERT INTO countries(id, code, name) VALUES ('VAT', 'VA', 'Vatican City');
INSERT INTO countries(id, code, name) VALUES ('VCT', 'VC', 'St Vincent and Grenadines');
INSERT INTO countries(id, code, name) VALUES ('VEN', 'VE', 'Venezuela');
INSERT INTO countries(id, code, name) VALUES ('VGB', 'VG', 'British Virgin Islands');
INSERT INTO countries(id, code, name) VALUES ('VIR', 'VI', 'U.S. Virgin Islands');
INSERT INTO countries(id, code, name) VALUES ('VNM', 'VN', 'Vietnam');
INSERT INTO countries(id, code, name) VALUES ('VUT', 'VU', 'Vanuatu');
INSERT INTO countries(id, code, name) VALUES ('WLF', 'WF', 'Wallis and Futuna');
INSERT INTO countries(id, code, name) VALUES ('WSM', 'WS', 'Samoa');
INSERT INTO countries(id, code, name) VALUES ('XKX', 'XK', 'Kosovo');
INSERT INTO countries(id, code, name) VALUES ('YEM', 'YE', 'Yemen');
INSERT INTO countries(id, code, name) VALUES ('MYT', 'YT', 'Mayotte');
INSERT INTO countries(id, code, name) VALUES ('ZAF', 'ZA', 'South Africa');
INSERT INTO countries(id, code, name) VALUES ('ZMB', 'ZM', 'Zambia');
INSERT INTO countries(id, code, name) VALUES ('ZWE', 'ZW', 'Zimbabwe');
INSERT INTO countries(id, code, name) VALUES ('ENG', 'EL', 'England');
INSERT INTO countries(id, code, name) VALUES ('NIR', 'ND', 'Northern Ireland');
INSERT INTO countries(id, code, name) VALUES ('SCO', 'OL', 'Scotland');
INSERT INTO countries(id, code, name) VALUES ('WAL', 'WL', 'Wales');
